my_list = [10, 20, 30, 40, 50]
print("Original List:", my_list)
my_list.append(60)
print("After append(60):", my_list)
my_list.extend([70, 80])
print("After extend([70, 80]):", my_list)
my_list.insert(2, 25)
print("After insert(2, 25):", my_list)
my_list.remove(40)
print("After remove(40):", my_list)
removed = my_list.pop()
print("After pop():", my_list)
print("Popped Element:", removed)
print("Index of 30:", my_list.index(30))
my_list.append(20)
print("After append(20):", my_list)
print("Count of 20:", my_list.count(20))
my_list.sort()
print("After sort():", my_list)
my_list.reverse()
print("After reverse():", my_list)
new_list = my_list.copy()
print("Copied List:", new_list)
new_list.clear()
print("After clear() on copied list:", new_list)
print("Length of Original List:", len(my_list))